[package]
name = "halo2_project"
version = "0.1.0"
edition = "2021"

[dependencies]
halo2 = { package = "halo2_proofs", git = "https://github.com/privacy-scaling-explorations/halo2", tag = "v2023_04_20" }
rand = "0.8.5"
